---
name: CI
env:
  APPLICATION_NAME   : "MyFlask"  
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  my_build_job:
    runs-on: ubuntu-latest
    steps:
      
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Execute few commands 
        run: |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
      - name: List current folder
        run: ls -la
  my_test_job: 
    runs-on: ubuntu-latest
    needs: [my_build_job]
    steps:
      - name: Run a multi-line script
        run:  echo "Add other actions to build"
      - name: Deploy package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
          
