---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  my_build_job:
    runs-on: ubuntu-latest
    steps:
      
      - name: Run a one-line script
        run: echo "Hello, world!"
  my_test_job: 
    runs-on: ubuntu-latest
    needs: [my_build_job]
    steps:
      - name: Run a multi-line script
        run:  echo "Add other actions to build"
          
